project:
  type: website
  output-dir: docs

website:
  title: "Daniel Choi"
  navbar:
    left:
      - text: "Writing"
        href: writing.qmd
      - text: "Resume"
        href: experience.qmd
format:
  html:
    theme: litera
    css: styles.css
