project:
  type: website
  output-dir: docs

website:
  title: "Daniel Choi"
  navbar:
    right:
      - writing.qmd
      - experience.qmd
      # - icon: github
      #   href: https://github.com/xrontux
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
