---
title: "Inner Duality"
description: ""
author: "Daniel Choi"
date: "2024-07-30"
---

Just a quick self reflection of my inner state of mind.

Recently, I am becoming more aware that my mind is a temple of contradictions, a complex neural web where my thoughts and emotions are unfortunately and perpetually at odds. 

For instance, I often think that I deserve better opportunities and a brighter future. Yet deep within, I also feel unworthy of the challenges that lie ahead. It's a paradox I grapple with daily — believing in my potential while simultaneously doubting my capabilities. It’s like an endless mental tug-of-war where there is no winner, because I am pulling from both sides, constantly adjusting the weights of my beliefs and values into disarray. 

I am also materialistic in many ways, driven by the allure of wealth and success. Yet, I despise this yearning for material possessions, recognising the emptiness it often brings. This internal conflict generates constant tension, a perpetual struggle between my aspirations and my principles.

I set high expectations for myself, envisioning great achievements and significant milestones. However, I frequently feel that I have little to show for these aspirations, as if my dreams are always just out of reach. I believe that this dichotomy between my ambitions and my perceived accomplishments is fuelling the relentless cycle of self-criticism and discontent.

My living circumstances present their own set of challenges, adding to the complexity of my internal struggle. I am acutely aware of my good fortune and circumstances compared to many others, yet I can't shake the feeling of being profoundly unlucky. It's a peculiar state of mind, feeling both blessed and burdened at the same time. Am I mentally unwell? Or is this just my mind’s distasteful way of keeping me on my toes with its own cosmic jest?

In this interplay of contradictions, I find myself desperately seeking balance to soothe the chaos within, striving to reconcile my thoughts with my feelings, my desires with my values, and my expectations with my reality. It’s a journey of self-discovery and acceptance, weaving together the boundaries of who I am and who I aspire to be.

Maybe this is just what being young is all about — trying to make sense of it all while the universe chuckles at our efforts.



