---
title: "My take on happiness"
description: ""
author: "Daniel Choi"
date: "2024-06-15"
---
Looking back, the first 20 years of my life seemed to lack a sense of purpose.

I studied because I was a student, learned new sports because I was part of a club, attended church because I was a Christian, and so on. It felt as though my actions were dictated by my environment rather than my own desires. I didn’t give it much thought until I found myself at a crossroads, contemplating my future after graduating from university.

This was uncharted territory for me. For the first time, I had to think for myself. Life had been simpler when my primary concerns were upcoming exams or being late for class. Now, I had to consider what I wanted to do for the rest of my life.

The prospect of working was unsettling — committing to an indefinite career within a finite lifespan. What if I hated my first job? What if the work I did held no personal value? This was when I truly began to think about how I could lead a happy life.

On one hand, the materialistic side of me thought, wouldn't becoming wealthy and buying whatever I wanted make me happy? Yet another part of me found it foolish to exchange my dwindling time for money that would ultimately be worthless in death. People place immense value on scarce commodities and material wealth, yet they readily trade their even scarcer time for them. It seemed absurd that the average person spends the first 60 years of their life accumulating wealth, only to realize they don't have much time left. There had to be a way to feel fulfilled and satisfied every day, right?

Would the number of zeros in my bank account or the sight of green stock charts bring a wide grin to my face on my deathbed? Or would happiness be found in knowing that I devoted my life to helping others? What would happiness look like in those final moments? I've yet to find out.

A philosopher once said that much of our unhappiness stems from confusing elements within our control with those beyond it — believing we can control what is inherently uncontrollable. Achieving great wealth may not be within my control because the effort-to-reward ratio is not something I can manipulate. There are people who work 16 hours a day for minimum wage while others amass wealth effortlessly. While we can aim and shoot to the best of our abilities, factors like the wind can still divert the arrow.

For now, my conclusion is that I should focus on are things that I do have control over, which is the process, my approach to life, my values, and so on. The answer seems simple: to do the best I can under given circumstances and find happiness in knowing I did my best. However, the paradox of that simple concept is that, for me, it is very hard. Perhaps I have yet to find what I truly enjoy doing for the rest of my life, and I sincerely hope that I find my own answer.

For now, I will devote myself fully to this search.



